default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: Backend-test_development
  username: root
  password: root

test:
  <<: *default
  database: Backend-test_test
  username: root
  password: root

production:
  <<: *default
  database: Backend-test_production
  username: Backend-test
  password: <%= ENV['BACKEND-TEST_DATABASE_PASSWORD'] %>
